### ISSUE TITLE
HTTP 500 - No "exports" main defined in /node_modules/@nuxt/kit/package.json

### ISSUE THREAD

**Issue by kuebli** [inkline/plugin#1]
Nuxt startup not possible, it shows an HTTP 500 error.
 I've followed the instructions of the official guide: https://next.inkline.io/docs/installation/nuxt

```
[nuxt] [request error] [unhandled] [500] No "exports" main defined in /home/projects/nuxt-starter-jhz8jh/node_modules/@nuxt/kit/package.json
  at get (https://nuxtstarterjhz8jh-ofn3.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:344852)  
  at get (./node_modules/h3/dist/index.mjs:238:11)  
  at normalizeError (./.nuxt/dev/index.mjs:441:18)  
  at errorhandler (./.nuxt/dev/index.mjs:460:71)  
  at toNodeHandle (./node_modules/h3/dist/index.mjs:1430:27)
```

Reproduction: https://stackblitz.com/edit/nuxt-starter-jhz8jh 
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `plugins`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

**Comment by kuebli** [comment]
Commit https://github.com/inkline/cli/commit/60bc4f88dfa36fe766eed4ed522f2797042c4cbc resolved the issue.
